@echo off
echo Starting Chrome with remote debugging...
start "" "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir="C:\chrome-debug"
echo Waiting for Chrome to start...
timeout /t 10 /nobreak
echo Running the email sending tests...
cd /d "c:\Users\Darsh\Desktop\frmwrk"
mvn exec:java "-Dexec.mainClass=org.testng.TestNG" "-Dexec.args=testng.xml"
echo Tests completed. Closing Chrome...
taskkill /f /im chrome.exe
echo Done.
pause